apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bank-ingress
  namespace: bankapp-namespace
  
spec:
  ingressClassName: traefik

  rules:
  - host: bank.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bank-service
            port:
              number: 80
